### ISSUE TITLE
SecInf Test-TargetResource can return value other than true

### ISSUE THREAD

**Issue by zjalexander** [jcwalker/SecurityPolicyDsc#4]
https://github.com/jcwalker/SeceditDsc/blob/dev/DSCResources/MSFT_SecInf/MSFT_SecInf.psm1#L100
https://github.com/jcwalker/SeceditDsc/blob/dev/DSCResources/Library/Helper.psm1#L211
Ralph Kyttle reported the following issue to me on WS2016, and I think it's in the above lines of code - the output of secedit.exe can return a value which PS treats as a return in the function. Piping to out-null should fix this, like I did here: https://github.com/zjalexander/AuditPolicyDsc/blob/master/DSCResources/Helper.psm1#L385 

```
PS C:\Program Files\DSC-EA\Output> Test-DscConfiguration -ComputerName DSCTEST10 -ReferenceConfiguration 'C:\Program Files\DSC-EA\localhost.mof'
WARNING: [DSCTEST10]:                            [[SecInf]SecurityTemplate] Cannot bind argument t
o parameter 'ReferenceObject' because it is null.
The PowerShell DSC resource C:\Program 
Files\WindowsPowerShell\Modules\SeceditDSC\DscResources\MSFT_SecInf returned results in a format 
that is not valid. The results from running Test-TargetResource must be the boolean value True 
or False.
    + CategoryInfo          : InvalidResult: (root/Microsoft/...gurationManager:String) [], CimE 
   xception
    + FullyQualifiedErrorId : TestTargetResourceInvalidResultFormat
    + PSComputerName        : DSCTEST10 
```

**Comment by jcwalker** [comment]
Made the suggested corrections @zjalexander suggested to MSFT_SecInf.psm1 but not to Helper.psm1 as the line of code in question is not executed in Test-TargetResource.

**Comment by rkyttle** [comment]
Thanks Jason!  I was able to test and this is working correctly now.
